name: Deploy Frontend & Backend to cPanel Domain

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------- FRONTEND ----------
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'npm'
          cache-dependency-path: nexoraspace-frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: nexoraspace-frontend
        run: npm ci

      - name: Build Vite App (Frontend)
        working-directory: nexoraspace-frontend
        run: npm run build

      - name: Install Rsync & SSH Tools
        run: |
          echo "Installing rsync & sshpass..."
          sudo apt-get update -y
          sudo apt-get install -y rsync sshpass

      - name: Deploy Frontend to cPanel Server
        run: |
          echo "🚀 Deploying frontend to cPanel..."
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='.htaccess' \
            --exclude='.env' \
            -e "sshpass -p '${{ secrets.CPANEL_PASSWORD }}' ssh -o StrictHostKeyChecking=no" \
            ./nexoraspace-frontend/dist/ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:/home/sewturbhe/nexoraspace.vishalsharmadev.in/

      # ---------- BACKEND ----------
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Build Backend (if you have a build script)
        working-directory: backend
        # if you don't have a build script, this step will succeed but do nothing.
        run: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "No backend build script; skipping build."
          fi

      - name: Deploy Backend to cPanel Server
        run: |
          echo "🚀 Deploying backend to cPanel..."
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='.env' \
            --exclude='node_modules/' \
            -e "sshpass -p '${{ secrets.CPANEL_PASSWORD }}' ssh -o StrictHostKeyChecking=no" \
            ./backend/ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:/home/sewturbhe/api.nexoraspace.vishalsharmadev.in/

      - name: Trigger app restart on server (Passenger / cPanel)
        run: |
          echo "Attempting to trigger app restart on server..."
          sshpass -p '${{ secrets.CPANEL_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} \
            'cd /home/sewturbhe/api.nexoraspace.vishalsharmadev.in 2>/dev/null && mkdir -p tmp && touch tmp/restart.txt || echo "Passenger restart file not created (maybe not using Passenger)."'

      - name: Confirm Deployment
        run: echo "✅ Deployment completed successfully!"
