name: Deploy React to cPanel Domain

on:
  push:
    branches:
      - main  # Runs on every push to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Display Node.js Version (for debugging)
    - name: Display Node.js Version
      run: node -v

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        cd nexoraspace-frontend
        npm install

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        cd nexoraspace-frontend
        npm test -- --watchAll=false

    # Step 5: Build React App
    - name: Build React App
      run: |
        echo "Building React App..."
        cd nexoraspace-frontend
        npm run build

    # Step 6: Install Rsync & SSH Tools
    - name: Install Rsync & SSH Tools
      run: |
        echo "Installing rsync & sshpass..."
        sudo apt-get install -y rsync sshpass

    # Step 7: Deploy via Rsync (Only Changed Files)
    - name: Deploy to cPanel Server
      run: |
        echo "Deploying files to cPanel..."
        rsync -avz --delete --exclude='.git/' --exclude='.htaccess' --exclude='.env' \
        -e "sshpass -p '${{ secrets.CPANEL_PASSWORD }}' ssh -o StrictHostKeyChecking=no" \
        nexoraspace-frontend/build/ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:/home/sewturbhe/nexoraspace.vishalsharmadev.in/

    # Step 8: Confirm Deployment
    - name: Confirm Deployment
      run: echo "✅ Deployment completed successfully!"
